modify readme link
amazon-connect/amazon-connect-chat-interface pull request #143
Opened 2023-07-08 19:06 UTC by williankargo

*Issue #, if available:*

*Description of changes:*
I gonna change the document on the link: https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/cloudformationTemplates/startChatContactAPI
by removing #prebuild-chat-widget from the original url, users can see my new description which is essential to read at the beginning of the doc.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-07-12 22:02 UTC, spencerlepine requested changes
.. outdated comment

2023-07-13 20:52 UTC, spencerlepine requested changes

2023-07-13 23:10 UTC, williankargo commented on .github/docs/built-in-script-setup-setps.md
yes

2023-07-13 23:20 UTC, williankargo commented on .github/docs/built-in-script-setup-setps.md
> +# Use the customized version of amazon-connect-chat-interface.js in a quick way
yes. and I think we should only put one code section in the document so customers won't feel confused.

2023-07-13 23:21 UTC, williankargo commented on .github/docs/screenshoots/built-in-script-setup-steps-change-color.jpg
ok

2023-07-18 17:12 UTC, spencerlepine approved these changes
🚢

2023-08-09 20:05 UTC, spencerlepine commented
Note for later: need to merge https://github.com/amazon-connect/amazon-connect-chat-interface/pull/161 afterwards

2023-08-14 17:20 UTC, spencerlepine requested changes

2023-08-14 17:20 UTC, spencerlepine commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md.md
Could we fix file name to be: `HostedSnippetCustomBundleFileSetup.md`?

2023-08-15 18:56 UTC, williankargo commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md.md
yes

2023-08-21 16:00 UTC, spencerlepine approved these changes

2023-09-25 17:05 UTC, spencerlepine commented
-Need to remove `%20` before file name
-Need to update # comment with // for javascript

2023-09-25 17:07 UTC, spencerlepine requested changes

2023-09-25 17:07 UTC, spencerlepine commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md
> +    ![Alt text](screenshoots/built-in-script-setup-steps-s3.jpg)
need to rename to screenshots not screenshoots

2023-09-25 17:07 UTC, spencerlepine commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md
> +        amazon_connect('customerChatInterfaceUrl', 'https://...'); # TODO: put in your link to amazon-connect-chat-interface.js
need to fix comment to use // not #

2023-09-25 17:07 UTC, spencerlepine commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md
> ++ amazon_connect('customerChatInterfaceUrl', 'https://...'); # TODO: put in your link to amazon-connect-chat-interface.js
need to fix comment to use // not #

2023-09-25 17:07 UTC, spencerlepine commented on .github/docs/ HostedSnippetCustomBundleFileSetup.md
> +# Host Widget Snippet Integrated Custom UI (S3 Bucket/CDN)
fix file name to be `HostedSnippet...` not ` HostedSnippet...`

2023-09-25 17:18 UTC, spencerlepine commented on .github/docs/screenshots/built-in-script-setup-steps-lmaw.jpg
need to blur cloudfront

2023-09-26 21:32 UTC, spencerlepine commented
Had to rename file, re-opened and co-authored in: https://github.com/amazon-connect/amazon-connect-chat-interface/pull/185

2023-09-26 21:32 UTC, closed without merging